### ISSUE TITLE
Fear/footer

### ISSUE THREAD

**Issue by sookyoungwoo** [JJOK-PROJECT/web_frontend#13]
### ✨ Describe

푸터를 만듭니다

### ✅ Tasks

- [ ] HRDKOREA 내용 쓰기
- [ ] 팀원들 깃허브나 이메일 주소
- [ ] 학교 이름 넣기
- [ ] 민원 접수 링크
