### ISSUE TITLE
feat/metabus

### ISSUE THREAD

**Issue by sookyoungwoo** [JJOK-PROJECT/web_frontend#14]
### ✨ Describe

학교 로드뷰를 띄웁니다!

### ✅ Tasks

- [ ] 학교 로드뷰 띄우기
- [ ] 자세히 보기 클릭했을 때 새 창으로 크게띄우기
- [ ] 로드뷰 부가 설명 띄우기
