### ISSUE TITLE
Feat/Community

### ISSUE THREAD

**Issue by sookyoungwoo** [JJOK-PROJECT/web_frontend#9]
### ✨ Describe

커뮤니티 Nav바를 만듭니다.

### ✅ Tasks

- [x] 커뮤니티 nav바
- [x] 일반/익명/뜨끈조언 카테고리 만들기
- [x] 눌렀을 때 각각 페이지로 이동
- [x] 누른 버튼 밑에 줄 그어서 표시
- [x] 눌러진 버튼 더 진한색으로 표시

**Comment by sookyoungwoo** [comment]
WWWWWWWWOWOWOWOOWOWOWOW
